name: "Broadlink Manager"
description: "Easely learn and send IR/RF Command"
codenotary: tomer.klein@gmail.com
version: "5.8.4"
slug: "broadlink_manager"
panel_icon: mdi:remote
# panel_admin: false
# hassio_api: true
# hassio_role: manager
ingress: true
ingress_port: 7020
ingress_stream: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
startup: before
host_network: true
ports:
  7020/tcp: 7020
ports_description:
  7020/tcp: Web interface
webui: http://[HOST]:[PORT:7020]
url: https://github.com/t0mer/broadlinkmanager-docker
options:
  certfile: fullchain.pem
  keyfile: privkey.pem
  ssl: false
schema:
  certfile: str
  keyfile: str
  ssl: bool
  log_level: list(trace|debug|info|notice|warning|error|fatal)?

